### ISSUE TITLE
How to test my own RGB videos

### ISSUE THREAD

**Issue by happyCodingSusan** [villawang/CatNet#1]
Hi @villawang , thanks for sharing your great work!
I was wondering how to test your method on my own RGB videos.
Thanks for your kind reply!

**Comment by villawang** [comment]
Hi, you first need to create annotations like create_annotation.py in the dataset folder or you can write your own dataset wrapper. Then follow train and test steps.

**Comment by villawang** [comment]
> Hi @villawang , thanks for sharing your great work!
> I was wondering how to test your method on my own RGB videos.
> Thanks for your kind reply!

Hi, you first need to create annotations like create_annotation.py in the dataset folder or you can write your own dataset wrapper. Then follow train and test steps.
